version: '3.8'

services:
  web:
    build:
      context: ./project/backend
      dockerfile: Dockerfile
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./project/backend:/usr/src/
    environment:
      - DATABASE_URL=postgres://postgres:postgres@web-db:5432/test_db
    ports:
      - 8004:8000
    depends_on:
      - web-db

  web-db:
    build:
      context: ./project/backend/db
      dockerfile: Dockerfile
    expose:
      - 5432
    ports:
      - 5434:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - TZ=Asia/Tokyo
    volumes:
      - db-data:/var/lib/postgresql/data

  front:
      stdin_open: true
      build:
        context: ./project/frontend
        dockerfile: Dockerfile
      volumes:
        - ./project/frontend:/usr/src/
        - /usr/src/app/node_modules
      ports:
        - 3007:3000
      depends_on:
        - web

volumes:
  db-data:
    driver: local