version: '3.8'

services:
  web:
    build:
      context: ./project/backend
      dockerfile: Dockerfile.prod
    ports:
      - 8004:8000
    environment:
      - ENVIRONMENT=production
      - DATABASE_URL=postgres://postgres:postgres@web-db:5432/web_prod
    depends_on:
      - web-db


  web-db:
    build:
      context: ./project/backend/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres


  front:
    build:
      context: ./project/frontend
      dockerfile: Dockerfile.prod
      args:
        - NODE_ENV=production
        - REACT_APP_API_SERVICE_URL=${REACT_APP_API_SERVICE_URL}
    ports:
      - 3007:80
    depends_on:
      - web